# fly.toml app configuration file generated for cash-tracker-bot

app = "cash-tracker-bot"
primary_region = "fra"

[build]

[processes]
app = "python src/bot.py"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512MB"